# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"split_data": "00_core.ipynb",
         "split_data_by_time": "00_core.ipynb",
         "rmse": "00_core.ipynb",
         "print_score": "00_core.ipynb",
         "set_rf_samples": "00_core.ipynb",
         "reset_rf_samples": "00_core.ipynb",
         "run_rf_regressor": "00_core.ipynb",
         "predict": "00_core.ipynb",
         "get_tree_confidence": "00_core.ipynb",
         "rf_feat_importance": "00_core.ipynb",
         "rf_plot_fi": "00_core.ipynb",
         "get_pairs": "00_core.ipynb"}

modules = ["autoforest.py"]

doc_url = "https://fastai.github.io/autoforest/"

git_url = "https://github.com/fastai/autoforest/tree/master/"

def custom_doc_links(name): return None
