# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"split_data": "00_regressor.ipynb",
         "split_data_by_time": "00_regressor.ipynb",
         "rmse": "02_baysian_reg.ipynb",
         "set_rf_samples": "02_baysian_reg.ipynb",
         "reset_rf_samples": "02_baysian_reg.ipynb",
         "RfRegressor": "02_baysian_reg.ipynb",
         "CorrelatedColumns": "00_regressor.ipynb",
         "RfOptimizer": "00_regressor.ipynb",
         "fix_dataframe": "01_cleandata.ipynb",
         "split_by_date": "01_cleandata.ipynb",
         "display_all": "01_cleandata.ipynb",
         "add_datepart": "01_cleandata.ipynb",
         "is_date": "01_cleandata.ipynb",
         "fill_missing_numeric": "01_cleandata.ipynb",
         "fill_missing": "01_cleandata.ipynb",
         "df_shrink_dtypes": "01_cleandata.ipynb",
         "cont_cat_split": "01_cleandata.ipynb",
         "feature_importance": "02_baysian_reg.ipynb",
         "plot_feature_importance": "02_baysian_reg.ipynb",
         "get_cols_of_low_imp": "02_baysian_reg.ipynb",
         "calc_correlations": "02_baysian_reg.ipynb",
         "plot_correlation_heatmap": "02_baysian_reg.ipynb",
         "plot_var_linkage": "02_baysian_reg.ipynb",
         "get_correlation_pairs": "02_baysian_reg.ipynb",
         "print_result": "02_baysian_reg.ipynb",
         "print_result_diff": "02_baysian_reg.ipynb"}

modules = ["regressor.py",
           "cleaner.py",
           "reg.py"]

doc_url = "https://dangraf.github.io/autoforest/"

git_url = "https://github.com/dangraf/autoforest/tree/master/"

def custom_doc_links(name): return None
