# AUTOGENERATED! DO NOT EDIT! File to edit: 01_cleandata.ipynb (unless otherwise specified).

__all__ = ['fix_dataframe', 'split_by_date', 'display_all']

# Cell
import numpy as np
import pandas as pd
from pandas.api.types import  is_numeric_dtype, is_integer_dtype
import matplotlib.pyplot as plt
import re
from fastai.tabular.all import *

# Cell
def fix_dataframe(df, y_col_name, datefield=None, ):
    df_shrink_dtypes(df)
    if datefield is not None:
        df.sort_values(datefield, inplace=True)
        df = add_datepart(df, datefield)
    df[y_col_name] = np.log(df[y_col_name])
    return df

# Cell
def split_by_date(df, pct):
    validx_start = int(len(df)*(1-pct))
    train_split = list(range(0, validx_start))
    val_split = list(range(validx_start, len(df)))
    return (train_split, val_split)

# Cell
def display_all(df):
    with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000):
        display(df)